### PR TITLE
[FH #1] GITHUB TEMPLATE/Supporting OSS repo

### PR DESCRIPTION
**Pull request by vinhyenvodoi98**
# About Template
## Background
I created this template with the purpose so that developers can share their projects with the community and can receive support from the community.

## How to use
I use github's api to get information about the repo such as how many starts, forks, descriptions and topics...

The topic field is quite important because I want the user to enter his wallet address there in the first place
Screen Shot 2024-06-15 at 21 59 31

The reason I chose this is because I don't want to let the user enter wallet address in the process of using the template because it could lead to wallet tampering

## Problem
- ~I can run it locally but cannot use it on warpcast.com so could you help me to do it~
  - i deploy to https://frametrain-plum.vercel.app/ 
## Frame link
https://warpcast.com/taio-newgate/0xb98560a1
## Image
Screen Shot 2024-06-15 at 21 50 47

Screen Shot 2024-06-15 at 21 50 56

Screen Shot 2024-06-15 at 21 50 41

### CODE REVIEW

**Comment by vinhyenvodoi98** [comment]
@FTCHD 
when i try to use button `action: tx` it show this error
```
 ⨯ Error: Invalid button action.
```

**Comment by vinhyenvodoi98** [comment]
how to share frame to https://warpcast.com/ i copy url 

https://frametrain-plum.vercel.app/f/noen7z8n4qe85yi7k0ztkrzo

but it didn't show anything

**Comment by FTCHD** [comment]
Please pull the latest version of the `dev` branch, `tx` actions have been enabled.

This is how to use them:
tx

**Comment by FTCHD** [comment]
You may need to `JSON.stringify` the `txData` before sending it. It's still unexplored territory at the moment.

**Comment by FTCHD** [comment]
Nice idea btw, supporting OSS repos!

**Pull request closed without merging**
