### PR TITLE
[FH-1] lu.ma event preview frame

### PR DESCRIPTION
**Pull request by waptik**
# Lu.ma event page preview Template

## Background
Lu.ma is an online platform that allows event hosts to create  a page for their events. There are hosts and potential attendees on Farcaster from what i can tell. With a social graph image of a lu.ma's event page not working on farcaster as well being limited in basic information on it, this frame aims to solve this problem by allowing anyone to generate social card preview image of any event of lu.ma as a frame by only using the id of the event and share it with the community.
Users get to also choose the timezone they want the event date to be shown as.

## How to use (UPDATED)
1. Login into FrameTrain's dashboard
image
2. Choose the "Lu.ma Events Preview" template 
image
3. Visit any event page on lu.ma, copy the id from your URL tab, eg. If the event page url is `https://lu.ma/mn2vn0jw`, then the id is `mn2vn0jw`
image
4. Paste the ID inside the ID field
image
5. Choose the time zone  and font options then save your settings and Voilà!
image

 
## Issues / Complications
Because we are generating images on the fly, we are faced with image size limit. The maximum size limit for a frame is 256KB. I had to install `sharp`, which is also an option dependency of `next` (I think i should be available for template developers), to able to compress the image to be within a farcaster frame's image acceptable size limit. According to https://github.com/FTCHD/frametrain/wiki/%5BHACKATHONS%5D#relevant-details, i am free to install any dependencies i need.
I found out that on average, the image generated by satori(`@vercel/og`, `@next/og`) is at leadt ~1MB on average
image
image
image

 
## Frame link (UPDATED)
 https://warpcast.com/waptik/0x0e5e8139
 
## Screenshots of Frame in action (UPDATED)
image
image

### CODE REVIEW

**Comment by FTCHD** [comment]
Regarding this line: `https://luma-og.vercel.app/api/${config.eventId}` 

API calls to external services that are not publicly known and vetted is not allowed.

You cannot call external APIs that you own, it's one thing calling the 0x or OpenSea API, and another calling your own API that you host somewhere that is not recognized, not verified, and can change at any time.

In that sense, please move any logic inside FrameTrain, ideally client side in the Inspector. You can also create a `utils` file inside your templates folder and annotate it with `use server` if you need to run logic server side, although that is not needed in 99% of cases (and this template doesn't seem like an exception).

You can install npm packages that do this client side, but not use external API endpoints that are not validated and well known.

**Comment by waptik** [comment]
Got it. Thanks
I’m reverting changes to the previous version
The frame wasn’t loading for me in production that’s why I moved the code
externally

**Comment by waptik** [comment]
> Regarding this line: `https://luma-og.vercel.app/api/${config.eventId}`
> 
> API calls to external services that are not publicly known and vetted is not allowed.
> 
> You cannot call external APIs that you own, it's one thing calling the 0x or OpenSea API, and another calling your own API that you host somewhere that is not recognized, not verified, and can change at any time.
> 
> In that sense, please move any logic inside FrameTrain, ideally client side in the Inspector. You can also create a `utils` file inside your templates folder and annotate it with `use server` if you need to run logic server side, although that is not needed in 99% of cases (and this template doesn't seem like an exception).
> 
> You can install npm packages that do this client side, but not use external API endpoints that are not validated and well known.

Can i create an api route inside FrameTrain to handle the generation? It seems the size is too big when the generation is done  through server actions. I believe the same will be the if done client-side.

**Comment by FTCHD** [comment]
Thank you for the changes, it's unnerving that you keep not following feedback and guidelines for submitting a template.

All of your template's code must live inside the `templates` folder, adding arbitrary routes like `app/api/og/luma/[eventId]/route.tsx` will result in a declined entry. 

The size being too big is an issue that you need to fix, not circumvent through such hacks.

**Comment by FTCHD** [comment]
# Requests:

1. Upload a screenshot of your Frame in action
2. Post a link to your Frame in action
3. Add an option in your `Inspector.tsx` to let the User choose in what timezone the date/time is displayed. Use this timezone to convert and save the date/time to `config`.


# ⚠️⚠️⚠️
Do not query the event details every time. You do that in the Inspector once when the event id is inputed. That data is saved into the Frame's `config`, and the `config` is used to render the Frame. You do not save the `eventId` to the config, you save the final event data. I repeat, do not make an API call every time the Frame is called. You only need that data once and it doesn't update, so save it in the `config`.

**Comment by waptik** [comment]
@FTCHD I have implemented the suggestions you made. I installed `sharp` as a dependency to compress the image and also added an option to select a timezone.
Now, all the information is fetched right inside `Inspector` when the user clicks the "Save" button and the needed data is saved inside `config`

Please check the first comment for screenshot(s) and a link to the frame in action

**Comment by FTCHD** [comment]
Looks really good and you’re almost there. Leaving final feedback below:
1. Give the user the possibility to switch between square and wide ratio (see PDF template for example). Some covers look really bad wide, others look bad square. As we can see from the images you’ve attached above.
2. Allow the user to change the background of the banners that contain the text (OFFLINE, stavan, etc all those boxes). User picks one single color for all boxes.
3. Allow the user to change the text color of the banners. User picks one color for all texts.

**Comment by FTCHD** [comment]
About image handling/compression:

This is not the correct handling. There is no issue with using `sharp` (good idea), however there’s an issue if you’re using it on every request, without that being necessary. My bad if you wanted to save this image to R2 and I misunderstood. I thought you wanted to render the entire Cover component and save that, which would be wrong.

Let’s start from first principles. The issue is the image size, more specifically the size of the cover coming from Luma. That cover image is static, we can consider it to never change (as opposed to the details of the event).

In that sense, we can optimize the image and then upload it to the S3/R2 bucket. This is not the entire Cover component (our cover), it’s just the cover image from Luma. 

Note: It is strongly preferred to do this client-side, rather than on the server. We incur costs for everything happening on the server. However both options are valid.

Client Side: You can use `canvas` to create a hidden element on the image (invisible to the user) and use that to resize the image. See this: [reddit.com/r/learnjavascript/comments/y431sc/client_side_image_processing_package_like_sharp](http://reddit.com/r/learnjavascript/comments/y431sc/client_side_image_processing_package_like_sharp) and https://stackoverflow.com/a/75922364

Server Side: Create a file in your template’s folder and annotate it with `use server` at the top. This is a NextJS convention that makes the code run server-side, in here you can use `sharp`. Be aware that I haven’t tested this and it may not work as expected.

**Comment by FTCHD** [comment]
Please remove all changes on files such as `.gitignore`, `package.json` and  `.example.env` if they do not relate to your template.

**Comment by waptik** [comment]
> Please remove all changes on files such as `.gitignore`, `package.json` and `.example.env` if they do not relate to your template.

The changes in `.gitignore`  occurred when i ran the format script from the code snippet you showed me. No matter how many times i format it with the extension, no changes occur.

**Comment by FTCHD** [comment]
Just delete the change and commit, it will disappear from this PR.

**Comment by waptik** [comment]
@FTCHD The template is fully ready

**Pull request merged**
